{ pkgs, inputs, ... }:
{
  imports = [
    ./kitty.nix
    ./zsh.nix
    ./neovim.nix
    ./hyprland.nix
    ./theme.nix
  ];

  # Powerlevel10k prompt config (generated by wizard, kept as a file)
  home.file.".p10k.zsh".source = ../p10k.zsh;

  home.stateVersion = "23.11";
}
